In [1]:
import pandas as pd

In [2]:
dubai = pd.read_csv('dubai_data.csv')

In [3]:
dubai

,url,area,apartment type,size(sqm),bedrooms,age,price(USD/month),Walk-in Closet,Children's Play Area,Lobby in Building,...,Private Jacuzzi,View of Water,Children's Pool,Security,Partlyfurnished,Study,Furnished,Covered Parking,Shared Spa,Central A/C
0,https://www.propertyfinder.ae/en/plp/rent/apar...,Jumeirah Village Triangle,Apartment,74,1,9.0,1102.5000,0,1,0,...,0,0,0,1,0,0,0,1,0,1
1,https://www.propertyfinder.ae/en/plp/rent/town...,Dubai Land,Townhouse,158,3,NaN,2700.0000,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,https://www.propertyfinder.ae/en/plp/rent/apar...,Downtown Dubai,Apartment,124,2,6.0,4050.0000,0,0,0,...,0,1,0,0,0,0,1,0,0,0
3,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Creek Harbour (The Lagoons),Apartment,107,2,NaN,2812.4775,0,1,0,...,0,0,0,1,0,0,0,1,0,1
4,https://www.propertyfinder.ae/en/plp/rent/apar...,Jumeirah Beach Residence,Apartment,66,0,NaN,2137.5000,0,1,0,...,0,1,0,1,0,0,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7047,https://www.propertyfinder.ae/en/plp/rent/vill...,The Villa,Villa,334,5,NaN,5400.0000,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7048,https://www.propertyfinder.ae/en/plp/rent/apar...,DAMAC Hills,Apartment,65,2,2.0,1462.5000,0,0,0,...,0,1,0,1,0,0,0,1,0,1
7049,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Marina,Apartment,82,1,5.0,3375.0000,0,1,0,...,1,1,0,0,0,0,1,0,0,0
7050,https://www.propertyfinder.ae/en/plp/rent/apar...,Al Warqa'a,Apartment,93,1,NaN,855.0000,0,0,0,...,0,0,0,1,0,0,0,1,0,1
7051,https://www.propertyfinder.ae/en/plp/rent/vill...,The Springs,Villa,209,3,NaN,5062.5000,0,0,0,...,0,0,0,1,0,1,0,1,0,1

In [4]:
dubai.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7052 entries, 0 to 7051
Data columns (total 36 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   url                   7052 non-null   object
 1   area                  7052 non-null   object
 2   apartment type        7052 non-null   object
 3   size(sqm)             7052 non-null   int64
 4   bedrooms              7052 non-null   object
 5   age                   2424 non-null   float64
 6   price(USD/month)      7052 non-null   float64
 7   Walk-in Closet        7052 non-null   int64
 8   Children's Play Area  7052 non-null   int64
 9   Lobby in Building     7052 non-null   int64
 10  Balcony               7052 non-null   int64
 11  Private Pool          7052 non-null   int64
 12  Shared Gym            7052 non-null   int64
 13  ViewofLandmark        7052 non-null   int64
 14  Maids Room            7052 non-null   int64
 15  View of Landmark      7052 non-null   int64
 16  Private Garden        7052 non-null   int64
 17  Barbecue Area         7052 non-null   int64
 18  Maid Service          7052 non-null   int64
 19  Vastu-compliant       7052 non-null   int64
 20  Shared Pool           7052 non-null   int64
 21  Kitchen Appliances    7052 non-null   int64
 22  Pets Allowed          7052 non-null   int64
 23  Built in Wardrobes    7052 non-null   int64
 24  Concierge             7052 non-null   int64
 25  Private Gym           7052 non-null   int64
 26  Private Jacuzzi       7052 non-null   int64
 27  View of Water         7052 non-null   int64
 28  Children's Pool       7052 non-null   int64
 29  Security              7052 non-null   int64
 30  Partlyfurnished       7052 non-null   int64
 31  Study                 7052 non-null   int64
 32  Furnished             7052 non-null   int64
 33  Covered Parking       7052 non-null   int64
 34  Shared Spa            7052 non-null   int64
 35  Central A/C           7052 non-null   int64
dtypes: float64(2), int64(30), object(4)
memory usage: 1.9+ MB

In [5]:
dubai.describe()

,size(sqm),age,price(USD/month),Walk-in Closet,Children's Play Area,Lobby in Building,Balcony,Private Pool,Shared Gym,ViewofLandmark,...,Private Jacuzzi,View of Water,Children's Pool,Security,Partlyfurnished,Study,Furnished,Covered Parking,Shared Spa,Central A/C
count,7052.000000,2424.000000,7052.000000,7052.000000,7052.000000,7052.000000,7052.000000,7052.000000,7052.000000,7052.000000,...,7052.000000,7052.000000,7052.000000,7052.000000,7052.000000,7052.000000,7052.000000,7052.000000,7052.000000,7052.000000
mean,165.961146,6.180281,4399.510342,0.248157,0.424986,0.181792,0.777794,0.055445,0.624929,0.000142,...,0.037294,0.211571,0.141946,0.575723,0.023823,0.091889,0.283324,0.684628,0.126489,0.694271
std,159.836007,3.975483,5927.236822,0.431974,0.494376,0.385701,0.415759,0.228864,0.484176,0.011908,...,0.189496,0.408451,0.349019,0.494268,0.152508,0.288889,0.450644,0.464697,0.332423,0.460748
min,2.000000,2.000000,427.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,74.000000,3.000000,1462.500000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,115.000000,4.000000,2700.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,180.000000,9.000000,4950.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000
max,994.000000,16.000000,112500.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
dubai.head(10)

,url,area,apartment type,size(sqm),bedrooms,age,price(USD/month),Walk-in Closet,Children's Play Area,Lobby in Building,...,Private Jacuzzi,View of Water,Children's Pool,Security,Partlyfurnished,Study,Furnished,Covered Parking,Shared Spa,Central A/C
0,https://www.propertyfinder.ae/en/plp/rent/apar...,Jumeirah Village Triangle,Apartment,74,1,9.0,1102.5000,0,1,0,...,0,0,0,1,0,0,0,1,0,1
1,https://www.propertyfinder.ae/en/plp/rent/town...,Dubai Land,Townhouse,158,3,NaN,2700.0000,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,https://www.propertyfinder.ae/en/plp/rent/apar...,Downtown Dubai,Apartment,124,2,6.0,4050.0000,0,0,0,...,0,1,0,0,0,0,1,0,0,0
3,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Creek Harbour (The Lagoons),Apartment,107,2,NaN,2812.4775,0,1,0,...,0,0,0,1,0,0,0,1,0,1
4,https://www.propertyfinder.ae/en/plp/rent/apar...,Jumeirah Beach Residence,Apartment,66,0,NaN,2137.5000,0,1,0,...,0,1,0,1,0,0,1,1,0,1
5,https://www.propertyfinder.ae/en/plp/rent/vill...,Palm Jumeirah,Villa,622,4,NaN,29250.0000,1,1,0,...,0,1,0,1,0,0,1,1,0,1
6,https://www.propertyfinder.ae/en/plp/rent/town...,Dubai Waterfront,Townhouse,117,2,NaN,1451.2500,1,1,0,...,0,0,0,1,0,0,0,0,0,1
7,https://www.propertyfinder.ae/en/plp/rent/apar...,Downtown Dubai,Apartment,123,2,4.0,7875.0000,0,0,0,...,0,0,0,1,0,0,1,1,0,0
8,https://www.propertyfinder.ae/en/plp/rent/town...,Dubai Waterfront,Townhouse,117,2,NaN,1451.2500,0,1,0,...,0,0,0,1,0,0,0,0,0,1
9,https://www.propertyfinder.ae/en/plp/rent/vill...,Dubai Land,Villa,248,4,NaN,3375.0000,0,0,0,...,0,0,0,1,0,0,0,1,0,1

In [8]:
dubai.iloc[2]

url                     https://www.propertyfinder.ae/en/plp/rent/apar...
area                                                       Downtown Dubai
apartment type                                                  Apartment
size(sqm)                                                             124
bedrooms                                                                2
age                                                                   6.0
price(USD/month)                                                   4050.0
Walk-in Closet                                                          0
Children's Play Area                                                    0
Lobby in Building                                                       0
Balcony                                                                 1
Private Pool                                                            0
Shared Gym                                                              0
ViewofLandmark                                                          0
Maids Room                                                              0
View of Landmark                                                        1
Private Garden                                                          0
Barbecue Area                                                           0
Maid Service                                                            0
Vastu-compliant                                                         0
Shared Pool                                                             0
Kitchen Appliances                                                      0
Pets Allowed                                                            0
Built in Wardrobes                                                      0
Concierge                                                               0
Private Gym                                                             0
Private Jacuzzi                                                         0
View of Water                                                           1
Children's Pool                                                         0
Security                                                                0
Partlyfurnished                                                         0
Study                                                                   0
Furnished                                                               1
Covered Parking                                                         0
Shared Spa                                                              0
Central A/C                                                             0
Name: 2, dtype: object

In [9]:
db_apts = dubai[dubai["apartment type"] == "Apartment"]

In [10]:
db_apts

,url,area,apartment type,size(sqm),bedrooms,age,price(USD/month),Walk-in Closet,Children's Play Area,Lobby in Building,...,Private Jacuzzi,View of Water,Children's Pool,Security,Partlyfurnished,Study,Furnished,Covered Parking,Shared Spa,Central A/C
0,https://www.propertyfinder.ae/en/plp/rent/apar...,Jumeirah Village Triangle,Apartment,74,1,9.0,1102.5000,0,1,0,...,0,0,0,1,0,0,0,1,0,1
2,https://www.propertyfinder.ae/en/plp/rent/apar...,Downtown Dubai,Apartment,124,2,6.0,4050.0000,0,0,0,...,0,1,0,0,0,0,1,0,0,0
3,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Creek Harbour (The Lagoons),Apartment,107,2,NaN,2812.4775,0,1,0,...,0,0,0,1,0,0,0,1,0,1
4,https://www.propertyfinder.ae/en/plp/rent/apar...,Jumeirah Beach Residence,Apartment,66,0,NaN,2137.5000,0,1,0,...,0,1,0,1,0,0,1,1,0,1
7,https://www.propertyfinder.ae/en/plp/rent/apar...,Downtown Dubai,Apartment,123,2,4.0,7875.0000,0,0,0,...,0,0,0,1,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7045,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Sports City,Apartment,93,1,8.0,945.0000,0,0,1,...,1,0,0,1,0,0,0,1,0,1
7046,https://www.propertyfinder.ae/en/plp/rent/apar...,Al Nahda,Apartment,186,3,NaN,1350.0000,0,1,0,...,0,0,0,1,0,0,0,0,0,1
7048,https://www.propertyfinder.ae/en/plp/rent/apar...,DAMAC Hills,Apartment,65,2,2.0,1462.5000,0,0,0,...,0,1,0,1,0,0,0,1,0,1
7049,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Marina,Apartment,82,1,5.0,3375.0000,0,1,0,...,1,1,0,0,0,0,1,0,0,0
7050,https://www.propertyfinder.ae/en/plp/rent/apar...,Al Warqa'a,Apartment,93,1,NaN,855.0000,0,0,0,...,0,0,0,1,0,0,0,1,0,1

In [11]:
db_apts.describe()

,size(sqm),age,price(USD/month),Walk-in Closet,Children's Play Area,Lobby in Building,Balcony,Private Pool,Shared Gym,ViewofLandmark,...,Private Jacuzzi,View of Water,Children's Pool,Security,Partlyfurnished,Study,Furnished,Covered Parking,Shared Spa,Central A/C
count,5309.000000,2198.000000,5309.000000,5309.000000,5309.000000,5309.000000,5309.000000,5309.000000,5309.000000,5309.0,...,5309.000000,5309.000000,5309.000000,5309.000000,5309.000000,5309.000000,5309.000000,5309.000000,5309.000000,5309.000000
mean,105.778113,6.266151,3088.367308,0.225655,0.435864,0.228292,0.786589,0.022226,0.712564,0.0,...,0.031456,0.244114,0.162177,0.615935,0.028631,0.060463,0.326804,0.693351,0.149746,0.706913
std,61.602248,4.065872,3183.108044,0.418052,0.495916,0.419771,0.409754,0.147433,0.452609,0.0,...,0.174563,0.429601,0.368648,0.486419,0.166782,0.238366,0.469089,0.461146,0.356856,0.455221
min,4.000000,2.000000,427.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,69.000000,3.000000,1260.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,94.000000,4.000000,2137.500000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.0,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
75%,131.000000,10.000000,3712.500000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.0,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000
max,929.000000,16.000000,67500.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
pd.crosstab(db_apts["apartment type"], db_apts["Furnished"])

Furnished          0     1
apartment type
Apartment       3574  1735

In [13]:
db_apts.groupby(['Furnished']).median()

/var/folders/0y/1hyyp7y1761bc9sn7069rxx40000gn/T/ipykernel_12357/2144175568.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  db_apts.groupby(['Furnished']).median()

,size(sqm),age,price(USD/month),Walk-in Closet,Children's Play Area,Lobby in Building,Balcony,Private Pool,Shared Gym,ViewofLandmark,...,Private Gym,Private Jacuzzi,View of Water,Children's Pool,Security,Partlyfurnished,Study,Covered Parking,Shared Spa,Central A/C
Furnished,,,,,,,,,,,,,,,,,,,,,
0,94.0,5.0,1800.0000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1,91.0,4.0,3127.4775,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0

In [19]:
db_apts_1bed = db_apts[db_apts['bedrooms'] == '1']

In [20]:
db_apts_1bed

,url,area,apartment type,size(sqm),bedrooms,age,price(USD/month),Walk-in Closet,Children's Play Area,Lobby in Building,...,Private Jacuzzi,View of Water,Children's Pool,Security,Partlyfurnished,Study,Furnished,Covered Parking,Shared Spa,Central A/C
0,https://www.propertyfinder.ae/en/plp/rent/apar...,Jumeirah Village Triangle,Apartment,74,1,9.0,1102.5000,0,1,0,...,0,0,0,1,0,0,0,1,0,1
10,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Marina,Apartment,85,1,NaN,2137.5000,0,0,1,...,0,0,0,0,0,0,0,0,0,0
19,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Marina,Apartment,84,1,13.0,2925.0000,0,1,0,...,1,1,0,0,0,0,0,0,0,1
21,https://www.propertyfinder.ae/en/plp/rent/apar...,Jumeirah Village Triangle,Apartment,73,1,NaN,2137.4775,0,0,1,...,0,0,1,1,0,1,1,1,1,1
22,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Production City (IMPZ),Apartment,79,1,NaN,855.0000,0,1,1,...,0,0,0,1,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7030,https://www.propertyfinder.ae/en/plp/rent/apar...,Jumeirah Lake Towers,Apartment,79,1,11.0,1485.0000,0,0,0,...,0,1,0,1,0,0,0,0,0,1
7042,https://www.propertyfinder.ae/en/plp/rent/apar...,Business Bay,Apartment,92,1,12.0,1800.0000,1,1,1,...,0,1,1,1,0,0,0,1,1,0
7045,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Sports City,Apartment,93,1,8.0,945.0000,0,0,1,...,1,0,0,1,0,0,0,1,0,1
7049,https://www.propertyfinder.ae/en/plp/rent/apar...,Dubai Marina,Apartment,82,1,5.0,3375.0000,0,1,0,...,1,1,0,0,0,0,1,0,0,0
7050,https://www.propertyfinder.ae/en/plp/rent/apar...,Al Warqa'a,Apartment,93,1,NaN,855.0000,0,0,0,...,0,0,0,1,0,0,0,1,0,1

In [21]:
db_apts_1bed.median()

/var/folders/0y/1hyyp7y1761bc9sn7069rxx40000gn/T/ipykernel_12357/3515475763.py:1: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  db_apts_1bed.median()

size(sqm)                 77.0000
bedrooms                   1.0000
age                        5.0000
price(USD/month)        1799.9775
Walk-in Closet             0.0000
Children's Play Area       0.0000
Lobby in Building          0.0000
Balcony                    1.0000
Private Pool               0.0000
Shared Gym                 1.0000
ViewofLandmark             0.0000
Maids Room                 0.0000
View of Landmark           0.0000
Private Garden             0.0000
Barbecue Area              0.0000
Maid Service               0.0000
Vastu-compliant            0.0000
Shared Pool                1.0000
Kitchen Appliances         0.0000
Pets Allowed               0.0000
Built in Wardrobes         1.0000
Concierge                  0.0000
Private Gym                0.0000
Private Jacuzzi            0.0000
View of Water              0.0000
Children's Pool            0.0000
Security                   1.0000
Partlyfurnished            0.0000
Study                      0.0000
Furnished                  0.0000
Covered Parking            1.0000
Shared Spa                 0.0000
Central A/C                1.0000
dtype: float64

In [25]:
db_apts_1bed.groupby('area').median().sort_values(['price(USD/month)'], ascending=False)

/var/folders/0y/1hyyp7y1761bc9sn7069rxx40000gn/T/ipykernel_12357/3668689833.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  db_apts_1bed.groupby('area').median().sort_values(['price(USD/month)'], ascending=False)

,size(sqm),age,price(USD/month),Walk-in Closet,Children's Play Area,Lobby in Building,Balcony,Private Pool,Shared Gym,ViewofLandmark,...,Private Jacuzzi,View of Water,Children's Pool,Security,Partlyfurnished,Study,Furnished,Covered Parking,Shared Spa,Central A/C
area,,,,,,,,,,,,,,,,,,,,,
Bluewaters,107.0,4.0,7312.50000,0.0,0.5,0.0,1.0,0.0,0.5,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.5
City Walk,108.0,6.0,4331.25000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.5,0.0,0.0,0.5,1.0,0.0,1.0
Palm Jumeirah,106.0,2.0,4218.75000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
Dubai Harbour,68.0,2.0,4106.25000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.5,0.0,0.0,1.0,1.0,0.0,1.0
DIFC,83.0,NaN,3825.00000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Al Qusais,73.0,NaN,810.00000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
Al Warsan,79.5,4.0,798.08625,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai Land,79.0,6.0,787.50000,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai Industrial Park,83.5,NaN,776.23875,0.0,0.0,0.5,0.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.5,0.0,0.5
International City,69.0,2.0,720.00000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [26]:
pd.options.display.max_rows = len(db_apts_1bed)

In [27]:
db_apts_1bed.groupby('area').median().sort_values(['price(USD/month)'], ascending=False)

/var/folders/0y/1hyyp7y1761bc9sn7069rxx40000gn/T/ipykernel_12357/3668689833.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  db_apts_1bed.groupby('area').median().sort_values(['price(USD/month)'], ascending=False)

,size(sqm),age,price(USD/month),Walk-in Closet,Children's Play Area,Lobby in Building,Balcony,Private Pool,Shared Gym,ViewofLandmark,...,Private Jacuzzi,View of Water,Children's Pool,Security,Partlyfurnished,Study,Furnished,Covered Parking,Shared Spa,Central A/C
area,,,,,,,,,,,,,,,,,,,,,
Bluewaters,107.0,4.0,7312.50000,0.0,0.5,0.0,1.0,0.0,0.5,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.5
City Walk,108.0,6.0,4331.25000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.5,0.0,0.0,0.5,1.0,0.0,1.0
Palm Jumeirah,106.0,2.0,4218.75000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
Dubai Harbour,68.0,2.0,4106.25000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.5,0.0,0.0,1.0,1.0,0.0,1.0
DIFC,83.0,NaN,3825.00000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
Umm Suqeim,73.0,NaN,3600.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
The Hills,82.0,4.0,3487.50000,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Dubai Media City,65.0,NaN,3150.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0
Al Barari,110.0,NaN,3093.75000,0.0,0.0,0.0,0.5,0.0,0.5,0.0,...,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.0,0.5,0.5
Downtown Dubai,82.0,5.0,3037.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
Dubai Festival City,149.0,NaN,2925.00000,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Al Kifaf,83.0,3.0,2880.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Jumeirah,74.0,2.0,2868.75000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
Old Town,91.0,NaN,2812.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai Marina,78.0,12.0,2699.98875,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
Jumeirah Beach Residence,93.0,2.0,2587.50000,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Sheikh Zayed Road,84.0,NaN,2430.00000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
The Views,71.5,13.0,2385.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
Mohammed Bin Rashid City,73.0,2.5,2250.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Al Sufouh,71.0,9.0,2137.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
Business Bay,83.0,5.0,2025.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai Hills Estate,60.0,3.0,2025.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Jumeirah Lake Towers,78.0,11.0,1912.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
DuBiotech,62.0,5.0,1912.50000,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
Dubai Creek Harbour (The Lagoons),74.0,3.0,1912.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
Greens,71.0,7.0,1800.00000,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Karama,82.0,NaN,1743.75000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.5,0.0,0.0,0.5,0.0,0.5
Al Satwa,79.0,NaN,1687.47750,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Green Community,89.0,NaN,1631.25000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.5,1.0,0.0,0.5
Barsha Heights (Tecom),69.0,NaN,1620.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.5,0.0,0.0,0.5,0.0,0.0,1.0
Jumeirah Golf Estates,70.0,4.0,1575.00000,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Dubai Healthcare City,69.0,4.0,1575.00000,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Jumeirah Village Triangle,73.0,9.0,1574.98875,0.0,1.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.5,1.0,0.0,0.0,1.0,1.0,0.5,1.0
Culture Village,79.5,6.0,1518.73875,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.5,0.0,0.0,0.0,1.0,0.0,0.5
Nadd Al Sheba,81.0,NaN,1507.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
The Gardens,66.0,NaN,1462.50000,1.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
DAMAC Hills,75.0,2.0,1462.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
Meydan,55.0,3.0,1462.50000,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Al Jaddaf,81.0,2.0,1417.47750,0.0,1.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Al Barsha,79.0,3.0,1383.75000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Arjan,73.5,4.0,1350.00000,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Motor City,98.0,4.0,1350.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
Jumeirah Village Circle,73.5,5.0,1338.73875,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Bur Dubai,84.0,NaN,1327.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Jebel Ali,65.5,3.0,1293.75000,1.0,0.5,0.0,0.5,0.0,1.0,0.0,...,0.0,0.0,0.5,1.0,0.0,0.5,0.0,0.5,0.5,1.0
Al Mina,83.5,NaN,1248.75000,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai Science Park,75.0,NaN,1237.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Al Furjan,74.0,6.0,1237.50000,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
Al Khail Heights,126.0,6.0,1237.50000,0.0,1.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Umm Hurair,91.5,NaN,1203.75000,1.0,0.5,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.5,1.0,0.0,0.0,0.0,1.0,0.5,1.0
Dubai Studio City,69.0,5.0,1170.00000,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0
Deira,78.0,NaN,1125.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
Al Badaa,93.0,NaN,1125.00000,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
Discovery Gardens,90.0,NaN,1124.97750,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
Mirdif,100.5,NaN,1080.00000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
Downtown Jebel Ali,75.0,10.0,1080.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Town Square,49.0,4.0,1080.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Majan,88.0,NaN,1012.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai Sports City,71.0,8.5,1012.50000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
Academic City,84.0,NaN,1012.50000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Al Quoz,66.0,NaN,1012.50000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
Dubai Silicon Oasis,78.0,9.0,990.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Nadd Al Hammar,93.0,NaN,945.00000,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Remraam,62.0,12.0,933.75000,0.0,0.5,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Ras Al Khor,79.0,NaN,922.50000,0.0,0.5,0.5,1.0,0.0,0.5,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.5,0.0,1.0
Dubai Residence Complex,73.0,2.0,911.25000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai South (Dubai World Central),68.0,3.0,900.00000,0.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.5,1.0,0.0,1.0
Dubai Investment Park,79.5,12.0,888.73875,0.0,0.5,0.0,0.5,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Al Nahda,84.0,NaN,877.50000,0.0,0.0,0.0,1.0,0.0,0.5,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Al Muhaisnah,83.0,NaN,855.00000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai Production City (IMPZ),75.0,10.0,854.88750,0.0,0.0,0.5,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Al Warqa'a,78.0,NaN,832.50000,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai Waterfront,65.0,9.0,810.00000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Al Qusais,73.0,NaN,810.00000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
Al Warsan,79.5,4.0,798.08625,0.0,0.0,1.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai Land,79.0,6.0,787.50000,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
Dubai Industrial Park,83.5,NaN,776.23875,0.0,0.0,0.5,0.5,0.0,0.0,0.0,...,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0.5,0.0,0.5
International City,69.0,2.0,720.00000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0